services:
  kiwix:
    image: ghcr.io/kiwix/kiwix-serve:latest
    entrypoint: ["/bin/sh", "-c", "/usr/local/bin/kiwix-serve --port=8080 /data/zim/*.zim"]
    volumes:
      - ./data/zim:/data/zim:ro
    ports:
      - "8080:8080"
    restart: on-failure

  mbtileserver:
    image: ghcr.io/consbio/mbtileserver:latest
    command: --port 8081 --dir /data/maps
    volumes:
      - ./data/maps:/data/maps:ro
    ports:
      - "8081:8081"
    restart: on-failure
